### ISSUE TITLE
sha1 mismatch installing cloudfoundry-cli 6.12 from homebrew

### ISSUE THREAD

**Issue by mdcarlson** [pivotal/homebrew-tap#46]
Getting a sha1 signature mismatch error running `brew install cloudfoundry-cli`

The `cloudfoundry-cli.rb` formula for the cloud foundry-cli has a sha1 value of `8dfca97225499195b5ce9bbfb9f38f423fba78c0`.

The value I get when running sha1sum against the `cloudfoundry-cli-6.12.0.0&source=homebrew` file in the homebrew cache  (`/Library/Caches/Homebrew`) is `34083026a2b747ba176c71a3f2b12eb994b2b1c1`

When I corrected the formula locally, CF 6.12 installs correctly from homebrew

**Comment by voelzmo** [comment]
Just ran into the same problem. However, here is what I get
{code}
$ shasum cloudfoundry-cli-6.12.0.0\&source\=homebrew
320e1e412f9d489acfc00043803643945eb33799  cloudfoundry-cli-6.12.0.0&source=homebrew
{code}

Don't know what I'm doing differently than @mdcarlson?

**Comment by mdcarlson** [comment]
Agree with volezmo.  The hash I get today is `320e1e412f9d489acfc00043803643945eb33799`

**Comment by voelzmo** [comment]
Well, this should never happen, right? Getting 3 different hashes for the same version. Seems like the build keeps publishing HEAD under the same version on the S3 bucket?

**Comment by nebhale** [comment]
Sorry about this @mdcarlson.  The `cf` tool's release process is causing differing artifacts to be created using the same version numbers, breaking not only the Homebrew tap, but any chance for serviceability.  I'm going to get to work with the `cf` team on how to solve this problem once and for all.
