### ISSUE TITLE
Cloudfoundry-CLI and bosh-init are not Pivotal products

### ISSUE THREAD

**Issue by voelzmo** [pivotal/homebrew-tap#56]
The [readme](https://github.com/pivotal/homebrew-tap/blob/master/README.md) states `This a brew tap repository containing a collection of "formulae" for Pivotal products.`

This might be true for all the other components in here, but the CF CLI and bosh-init are parts of the open source part of CF. Probably they should reside in their own `cloudfoundry` tap?

**Comment by nebhale** [comment]
It's been discussed for some time, but those teams have never done the leg work to move them.  Until that time, they continue to be hosted here.
