### ISSUE TITLE
Consider removing cloudfoundry-cli package

### ISSUE THREAD

**Issue by sslavic** [pivotal/homebrew-tap#67]
CF CLI homebrew package is now maintained and available via https://github.com/cloudfoundry/homebrew-tap so to avoid confusion maybe consider removing it from here.

**Comment by gregturn** [comment]
If so, you might to post a blog entry or two and done tweets so people aren't surprised.

**Comment by nebhale** [comment]
@sslavic The problem we have is that removing it from the tap, will effectively EOL current users.  They won't realize why the CLI isn't updating (assuming that no more changes are happening).  There's a way in the "main" Homebrew repository to indicate that a formula has moved, but sadly, no way in a tap...

**Comment by nebhale** [comment]
Now complete.
