### ISSUE TITLE
Formula.sha1 deprecation

### ISSUE THREAD

**Issue by ffittschen** [pivotal/homebrew-tap#79]
Hi,

I'm getting this warning every time I run `brew update && brew upgrade`:

> Warning: Calling Formula.sha1 is deprecated!
> Use Formula.sha256 instead.
> /usr/local/Library/Taps/pivotal/homebrew-tap/springxd.rb:6:in `<class:Springxd>'

So please update your formulas to use SHA256. 
According to [this document](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Checksum_Deprecation.md) there is a warning on the SHA1 checksum deprecation since March.

Thanks!

**Comment by mikesmithson** [comment]
I created a pull request to address this issue. Hopefully, it will be accepted.

**Comment by nebhale** [comment]
Complete in 1438d942025af4411c1c0bd65aed60e42a143b14
